on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: manuals
          path: "*.pdf"